### ISSUE TITLE
Ser ingenieria

### ISSUE THREAD

**Issue by Obijuan** [mdelaosa/Memoria_TFG#1]
He abierto esta issue para que **la cierres cuando ya seas ingenieria**. Será tu última tarea en la Universidad 😉️

Has hecho un trabajo muy bueno. ¡Enhorabuena! 

He probado la app AudioKotlin, y se ha instalado perfectamente y todo ha funcionado según lo esperado. Ahora ya puedo aprender un poquito sobre mesas de mezclas, practicando con tu app. Muchas gracias 😀️

![Screenshot_20230720_064801_AudioKotlin](https://github.com/mdelaosa/Memoria_TFG/assets/1286062/01090ae9-c1fd-4d23-b644-3100ba2c95d4)

**Comment by mdelaosa** [comment]
Muchas gracias por tu comentario con respecto a la aplicación y a todos los consejos que nos has ofrecido a mis compañeros/as y a mi durante todos los años en los que hemos coincidido en clase.

¡Cierro el issue! 🥇
